package video.downloader.free.now.videos.utils

object Tags {

    val stable_version = "stable_version"

    val TAG_JSON_OBJ = "jobj_req"

    val URL = "url"
    val URL_API = "urlApi"
    val ME = "me"
    val USER = "user"
    val USER_ID = "user_id"
    val BHARAT = "Bharat"
    val DATE = "Date"
    val query = "query"
    val month = "month"
    val DATABASE = "Database"
    val DATE_API = "date"
    val TIME_API = "time"
    val RIDE_TIME = "ride_time"
    val CURRENT_TIME = "current_time"
    val BID_TIME = "bid_time"
    val RIDE_DATE = "ride_date"
    val RIDE_STATUS = "ride_status"
    val RIDE_DETAIL = "ride_detail"
    val CURRENT_DATE = "current_date"
    val URL_RESPONSE = "urlResponse"
    val URL_POST = "urlPost"
    val TEST = "test"
    val testStatus = "testStatus"
    val logID = "logID"
    val logId = "logId"
    val feedback_yes = "1"
    val feedback_no = "0"
    val videoPath = "path"

    val test_id = "test_id"
    val testId = "testId"
    val TRACKER = "Tracker"
    val FORMATED = "formatted"
    val SERVICE = "service"
    val ERROR = "error"
    val log_id = "log_id"
    val RESULT = "result"
    val INTERNET = "intertnet"
    val RESULTS = "results"
    val LOG = "log"
    val PREF = "pref"
    val CGT_Prefs = "cgt_pref"
    val GCM = "GCM"
    val GCMtoken = "GCMtoken"
    val GPS = "GPS"
    val USER_TOKEN = "user_token"
    val LOGIN_STATUS = "loginStatus"
    val SKIP_STATUS = "skipStatus"
    val TWITTER_STATUS = "twitterStatus"
    val IS_SPLASH = "is_splash"
    val NULL = "null"
    val FACEBOOK = "facebook"

    val SUCCESS = "success"
    val FAILED = "failed"

    val USER_DATA = "userData"
    val TRIAL_TEST_RESULT = "trialTestResult"
    val ACCESS_TOKEN = "access_token"
    val accessToken = "accessToken"
    val LANGUAGE = "language"
    val LANGUAGE_ID = "language_id"
    val FAVOURITE_DATA = "favouriteData"

    /**
     * For facebook tags.
     */

    /**
     * For Login tags.
     */
    val ID = "id"
    val MEMBER_ID = "member_id"
    val DRIVER_ID = "driver_id"
    val DRIVER_NAME = "driver_name"
    val DRIVER_IMAGE = "driver_image"
    val DRIVER_PHONE = "driver_phone_no"
    val DRIVER_LOCATION = "driver_location"
    val DRIVER_LAT = "driver_lat"
    val DRIVER_LNG = "driver_lng"
    val RIDE_ID = "ride_id"
    val PUSHER = "pusher"
    val PUSHER_RECEIVED_ID = "pusher_received_id"
    val OLD_RIDE_ID = "old_ride_id"
    val NAME = "name"
    val loginType = "loginType"
    val IMG = "img"
    val PLATE_NO = "plate_no"
    val AMOUNT = "amount"
    val EMAIL = "email"
    val PHONE = "phone"
    val phone = "phone"
    val BIRTHDAY = "Birthday"
    val GENDER = "gender"
    val MALE = "male"
    val FEMALE = "female"
    val Male = "Male"
    val Female = "Female"
    val DOB = "dob"
    val DATA = "data"
    val DATA1 = "data1"
    val REL_DATA = "relData"
    val duration = "duration"
    val noise = "noise"
    val voice = "voice"
    val screenInteraction = "screenInteraction"
    val video_duration = "video_duration"
    val task_name = "task_name"
    val start_time = "start_time"
    val end_time = "end_time"
    val intro_text = "intro_text"
    val complete_text = "complete_text"
    val test_type = "test_type"
    val testing_device = "testing_device"
    val testing_device_mob = "testing_device_mob"
    val noCode = "noCode"
    val logourl = "logourl"
    val test_duration = "test_duration"
    val userFeedback = "userFeedback"
    val user_agent = "user_agent"
    val endTime = "endTime"
    val startTime = "startTime"
    val taskEndTime = "taskEndTime"
    val taskStartTime = "taskStartTime"
    val surveyAnswers = "surveyAnswers"
    val window_w = "window_w"
    val window_h = "window_h"
    val retake_count = "retake_count"


    val CODE = "code"
    val LANG_ID = "lang_id"
    val IS_LANG_CHANGED = "is_lang_changed"
    val IS_UPDATE = "is_update"
    val IS_VERIFY = "is_verify"
    val VERIFY_CODE = "verify_code"
    val FROM_PROFILE = "FromUpdateProfile"
    val MESSAGE = "message"
    val msg = "msg"
    val TRUE = "true"
    val FALSE = "false"
    val DEVICE_ID = "device_id"
    val DISTANCE = "distance"
    val DEVICE_TYPE = "device_type"
    val PROFILE = "profile"
    val FAV_LIST = "fav_list"
    val CAR_TYPE = "car_type"
    val CAR_TYPE_LIST = "car_type_list"
    val SEND_CODE = "SEND_CODE"
    val LOGIN = "login"
    val LOGOUT = "logout"

    val IS_FEMALE = "is_female"
    val TAXI_ID = "taxi_id"
    val FROM_ID = "from"
    val TO = "to"
    val FROM = "from"
    val PICTURE = "picture"
    val LINK = "link"
    val ICON = "icon"
    val TYPE = "type"
    val TYPES = "types"
    val STORY = "story"
    val STATUS = "status"
    val BID_STATUS = "bid_status"
    val STATUS_TYPE = "status_type"
    val OBJECT_ID = "object_id"
    val CREATED_TIME = "created_time"
    val UPDATED_TIME = "updated_time"
    val PAGING = "paging"
    val PAGE = "page"
    val TOTAL_PAGE = "total_page"
    val CURSORS = "cursors"
    val AFTER = "after"
    val BEFORE = "before"
    val LIKES = "likes"
    val COMMENTS = "comments"
    val SOURCE = "source"
    val FIELDS = "fields"
    val GRAPH_USER = "GraphUser"

    val COVER = "cover"
    val PREVIOUS = "previous"
    val NEXT = "next"

    val FRAG_NAME = "fragment_name"
    val SELECT_DRIVER = "select_driver"
    val SELECT_ONE_DRIVER = "select_one_driver"
    val MAIN_ACTIViTY = "LoginActivity"
    val TRIP_DETAILS = "TripDetails"
    val FIND_YOUR_RIDE = "FindYourRide"
    val FIND_YOUR_RIDE_LIST = "FindYourRideList"
    val PENDING_REQUEST = "PendingRequest"
    val FAMILY = "Family"
    val TRACKING_SERVICE = "tracking_service"

    /**
     * For Booking tags.
     */
    val LAT = "lat"
    val LNG = "lng"
    val TO_NAME = "to_name"
    val TO_ADD = "to_add"
    val TO_LAT = "to_lat"
    val TO_LNG = "to_lng"
    val FROM_NAME = "from_name"
    val FROM_ADD = "from_add"
    val FROM_LAT = "from_lat"
    val FROM_LNG = "from_lng"
    val LAT_LNG_COLLECT = "LatLngCollect"
    val PLACE_ID = "place_id"
    val PLACE_NAME = "place_name"
    val PLACE_ADD = "place_add"
    val STATE = "STATE"
    val ADDRESS = "address"
    val EDIT_ADDRESS = "EDIT_ADDRESS"
    val PLACE_LAT = "place_lat"
    val PLACE_LNG = "place_lng"
    val IS_TO = "is_to"
    val FAVOURITE_PLACE = "FavouritePlace"
    val FAV = "1"
    val UNFAV = "0"
    val ADD_FAV = "add_fav"
    val REMOVE_FAV = "remove_fav"
    val FAV_TYPE = "fav_type"
    val DRIVER = "driver"
    val NOTE = "note"
    val NOTI_ID = "noti_id"
    val DRIVER_COUNT = "driver_count"
    val ADDITIONAL_FEES = "additional_fees"
    val CURRENCY = "currency"
    val PROMO_CODE = "promo_code"
    val BOOK_RIDE = "book_ride"
    val DISCOUNT = "discount"
    val TYPE_DISCOUNT = "type_discount"
    val ESTIMATE_RIDE = "estimate_ride"
    val IS_RIDE_AVAILABLE = "isRideAvailable"
    val FARE = "fare"
    val ESTIMATE = "estimate"
    val CURRENT_ADD_FEES = "current_add_fees"
    val TAXI_TYPE = "taxi_type"
    val IS_FUTURE = "is_future"
    val IS_CURRENT = "is_current"
    val TIP = "tip"
    val COUNTRY = "country"
    val COUNTRY_CODE = "country_code"
    val ACTIVE = "active"
    val UNACTIVE = "unactive"
    val ACCEPT = "accept"
    val DECLINE = "decline"
    val RANGE = "range"
    val RANGEDAS = "rangedas"
    val RATING = "rating"
    val COMMENT = "comment"
    val DRIVER_RATING = "driver_rating"
    val RATING_PASSENGER = "rating_passenger"
    val RATING_DRIVER = "rating_driver"
    val RATING_COUNT_DRIVER = "rating_count_driver"

    val DRIVER_PLATE = "driver_plate"
    val DRIVER_DISTANCE = "driver_distance"
    val IS_DRIVER_BID = "is_driver_bid"
    val REMAINING_TIME = "remaining_time"

    val OFFSET = "offset"
    val TWITTER = "Twitter"
    val SHARING_TEXT = "Sharing_text"

    val AB_ID = "ab_id"
    val AT_ID = "at_id"
    val U_ID = "u_id"
    val CITY_FROM = "cityfrom"
    val CITY_TO = "cityto"
    val PICKUP = "pickup"
    val F_LAT = "f_lat"
    val F_LNG = "f_lng"
    val START_DATE = "startdate"
    val START_TIME = "starttime"
    val SEAT = "seat"
    val ADDED_DATE = "added_date"
    val DESTINATION = "destination"
    val PRICE = "price"
    val T_LAT = "t_lat"
    val T_LNG = "t_lng"
    val LATLNG = "latLng"
    val ZERO_RESULTS = "ZERO_RESULTS"

    val SECONDS = "seconds"
    val MINUTES = "minutes"
    val HOURS = "hours"
    val DAYS = "days"

    val FROM_MY_FRIENDS = "from_my_friends"

    val LOCATIONS = "locations"
    val STREET = "street"
    val GEOCODE_QUALITY = "geocodeQuality"
    val ADMIN_AREA_1type = "adminArea1Type"
    val ADMIN_AREA_3type = "adminArea3Type"
    val ADMIN_AREA_4type = "adminArea4Type"
    val ADMIN_AREA_5type = "adminArea5Type"
    val ADMIN_AREA_1 = "adminArea1"
    val ADMIN_AREA_3 = "adminArea3"
    val ADMIN_AREA_4 = "adminArea4"
    val ADMIN_AREA_5 = "adminArea5"

    val LOCALITY = "locality"
    val LONG_NAME = "long_name"
    val SORT_NAME = "sort_name"
    val COUNTRY_SORT_NAME = "country_sort_name"
    val COUNTRY_LONG_NAME = "country_long_name"
    val CITY_SORT_NAME = "city_sort_name"
    val CITY_LONG_NAME = "city_long_name"

    val ONE_HOUR = "one_hour"
    val FIFTEEN_MIN = "fifteen_min"
    val IS_DRIVER_RECEIVED = "is_dirver_received"

    val EVENT = "event"

    val param_authToken = "authToken"
    val auth_token = "auth_token"

    val LIST_ITEM_TRENDING = "LIST_ITEM_TRENDING"
    val uuid = "uuid"
    val applicationId = "applicationId"
    val GET = "get"
    val POST = "post"
    val auth_key = "auth_key"
    val authKey_param = "authKey"
    val authToken_param = "authToken"
    val countryCode_param = "countryCode"
    val mobileNumber_param = "mobileNumber"
    val userID_param = "userId"
    val verificationCode_param = "verificationCode"
    val firstName_param = "firstName"
    val lastName_param = "lastName"
    val emailAddress_param = "emailAddress"
    val gender_param = "gender"
    val dateOfBirth_param = "dateOfBirth"
    val file_param = "file"
    val customName_param = "customName"
    val addressLine1_param = "addressLine1"
    val postalCode_param = "postalCode"
    val latitude_param = "latitude"
    val longitude_param = "longitude"
    val city_param = "city"
    val country_param = "country"

    val AUTH_KEY = "AUTH_KEY"
    val AUTH_TOKEN = "AUTH_TOKEN"
    val MOBILE_NUMBER = "MOBILE_NUMBER"

    val INTEREST = "INTEREST"

    val rec_First_name = "first_name"
    val rec_Last_name = "last_name"
    val rec_portrait_id = "portrait_id"
    val rec_portrait_url = "portrait_url"
    val rec_date_of_birth = "date_of_birth"
    val rec_mobile_number = "mobile_number"
    val rec_country_code = "country_code"
    val rec_language_id = "language_id"
    val rec_timeZone_id = "timeZone_id"
    val rec_password = "password"

    val rec_address = "address"
    val rec_last_login_date = "last_login_date"
    val rec_modified_date = "modified_date"
    val rec_modified_by = "modified_by"
    val rec_record_satus = "record_satus"
    val rec_facebook_id = "facebook_id"

    val primary_address = "primary_address"
    val favourites = "favourites"
    val activities = "activities"
    val application_id = "application_id"
    val search_filter = "search_filter"
    val display_order = "display_order"


    val favourite_id = "favourite_id"

    val userId = "userId"
    val profile_pic = "profile_pic"
    val user_name = "user_name"
    val user_image = "user_image"
    val username = "username"
    val is_login = "is_login"
    val user_online__time_id = "user_online__time_id"
    val profileId = "profileId"

    val activity_id = "activity_id"
    val activity_index = "activity_index"
    val activity_type = "activity_type"

    val archive = "archive"

    val category_name = "category_name"
    val create_by = "create_by"
    val create_date = "create_date"

    val parentCategoryId = "parentCategoryId"
    val customName = "customName"
    val custom_name_rec = "custom_name"
    val addressLine1 = "addressLine1"
    val state = "state"
    val country = "country"
    val primary = "primary"
    val primaryAddress = "primaryAddress"
    val addressLine2 = "addressLine2"

    val address_line_1 = "address_line_1"
    val address_id = "address_id"
    val addressId = "addressId"
    val address_components = "address_components"
    val administrative_area_level_2 = "administrative_area_level_2"
    val types = "types"
    val long_name = "long_name"
    val postal_code = "postal_code"
    val geometry = "geometry"
    val result = "result"
    val location = "location"
    val tickets = "tickets"

    val DEFAULT_ADDRESS = "DEFAULT_ADDRESS"
    val icon_url = "icon_url"


    val category_id = "category_id"
    val parent_category_id = "parent_category_id"
    val label = "label"

    val Filter = "Filter"
    val Category = "Category"
    val SubCategory = "SubCategory"
    val Options = "Options"
    val propCode = "propCode"

    val sub_category_name = "sub_category_name"
    val scope = "scope"
    val status = "status"
    val frequency = "frequency"
    val testInfo = "testInfo"
    val testData = "testData"
    val activityId = "activityId"
    val perPage = "perPage"
    val page = "page"
    val sort = "sort"
    val img_filter = "img_filter"

    val size = "size"
    val direction = "direction"
    val properties = "properties"
    val ASC = "ASC"
    val DESC = "DESC"
    val content = "content"

    val searchFilter = "searchFilter"
    val displayOrder = "displayOrder"
    val activity_category = "activity category"
    val sub_category = "sub_category"
    val timing = "timing"

    val favouriteId_PARAM = "favouriteId"
    val facebookId = "facebookId"
    val facebook_id = "facebook_id"
    val social_id = "social_id"

    val rec_interestsCate = "interestCategories"
    val rec_interests = "interests"

    val SHORT_CUT = "SHORT_CUT"
    val categoryId = "categoryId"

    val ADDRESS_ID = "ADDRESS_ID"
    val rec_email = "email"

    val startDate = "startDate"
    val endDate = "endDate"
    val activityTypeId = "activityTypeId"
    val frequencyType = "frequencyType"
    val frequencySubType = "frequencySubType"

    val CANCEL = "CANCEL"
    val RETRY = "RETRY"
    val OK = "OK"

    val start_date = "start_date"
    val end_date = "end_date"
    val sub_frequency = "sub_frequency"
    val address_line_2 = "address_line_2"
    val user_added = "user_added"

    val subCategoryId = "subCategoryId"

    val create = "create"

    val timeCategoryId = "timeCategoryId"
    val timeRange = "timeRange"
    val dayOfWeek = "dayOfWeek"

    val morning = "morning"
    val afternoon = "afternoon"
    val evening = "evening"
    val night = "night"
    val custom = "custom"

    val value = "value"

    val SEARCH = "SEARCH"
    val CHOOSE = "CHOOSE"

    val time_category = "time_category"
    val time_category_id = "time_category_id"
    val time_range = "time_range"

    //    val Title = "Title"
    val distanceRange = "distanceRange"
    val locationType = "locationType"

    val distance_range = "distance_range"
    val activityMainCategory = "activityMainCategory"
    val exception = "exception"
    val feedback = "feedback"
    val feedback_id = "feedback_id"


    val approverUserId = "approverUserId"
    val totalPages = "totalPages"
    val CREATED_ACTIVITY = "CREATED_ACTIVITY"
    val CHOOSE_CATEGORY = "CHOOSE_CATEGORY"

    val img_location = "img_location"
    val AnyTime = "Anytime"
    val TIME_0 = "TIME_01"
    val TIME_1 = "TIME_1"
    val TIME_2 = "TIME_2"
    val TIME_3 = "TIME_3"
    val TIME_4 = "TIME_4"

    val apply = "apply"
    val TEMP_USER_DATA = "temp_userData"
    val TEMP_FB_DATA = "temp_fbData"
    val TEMP_INSTITUTION_MODEL = "temp_institutionModel"
    val day_of_week = "day_of_week"

    val distanceFromRange = "distanceFromRange"
    val distanceToRange = "distanceToRange"
    val parent = "parent"

    val categoryType = "categoryType"
    val subCategoryName = "subCategoryName"

    val CONNECTED = "CONNECTED"
    val message = "message"
    val portrait_url = "portrait_url"

    val MY_ACTIViTY = "MyActivity"
    val CHAT = "CHAT"
    val OPEN = "OPEN"
    val PUBNUB = "pubnub"

    val ALL_CHANNEL_SUBSCRIBED = "ALL_CHANNEL_SUBSCRIBED"

    val FILE = "FILE"
    val DELETE = "DELETE"
    val conversation_id = "conversation_id"

    val distance_from_range = "distance_from_range"
    val distance_to_range = "distance_to_range"
    val location_type = "location_type"
    val HOME = "HOME"
    val WORK = "WORK"
    val FRIENDS = "FRIENDS"
    val verified = "verified"

    val profileAccessId = "profileAccessId"
    val requester = "requester"
    val createDate = "createDate"
    val approvedDate = "approvedDate"
    val approvedBy = "approvedBy"
    val textToSearch = "textToSearch"
//    val category = "category"
//    val subCategory = "subCategory"
//
//    val Morning = "Morning"
//    val Evening = "Evening"
//    val Custom = "Custom"
//    val Afternoon = "Afternoon"

    val POSITION = "POSITION"
    val position = "position"
    val required = "required"
    val expected_time = "expected_time"
    val expected_clicks = "expected_clicks"
    val answer = "answer"
    val answer_type = "answer_type"
    val keyword_1 = "keyword_1"
    val keyword_2 = "keyword_2"
    val keyword_3 = "keyword_3"
    val use_voicerec = "use_voicerec"
    val use_post_ques = "use_post_ques"
    val success_type = "success_type"
    val five_second = "five_second"
    val isPrototype = "isPrototype"
    val surveyQuestions = "surveyQuestions"
    val post_ques_set_id = "post_ques_set_id"


    val institution_state_id = "institution_state_id"
    val institution_state_name = "institution_state_name"
    val institution_id = "institution_id"
    val other_ins_name = "other_ins_name"
    val institute_name = "institute_name"
    val institution_name = "institution_name"

    val response = "response"
    val region_name = "region_name"
    val slug = "slug"
    val phone_no = "phone_no"
    val contact_no = "contact_no"
    val ins_head_name = "ins_head_name"
    val ins_head_contact = "ins_head_contact"
    val department_name = "department_name"
    val other_department_name = "other_department_name"
    val modified = "modified"
    val role = "role"
    val is_verified = "is_verified"

    val student_detail = "student_detail"
    val confirm_password = "confirm_password"
    val activation_code = "activation_code"
    val suspand_status = "suspand_status"

    val login_type = "login_type"
    val gcm_token = "gcm_token"

    val dob = "dob"
    val city_name = "city_name"
    val image_thumb = "image_thumb"
    val fav_cat_id = "fav_cat_id"

    val slider_type = "slider_type"
    val slider_id = "slider_id"
    val banner_image = "banner_image"
    val clicks = "clicks"
    val slider_category = "slider_category"
    val tot_clicks_users = "tot_clicks_users"

    val img = "img"
    val click_status = "click_status"
    val thumb_status = "thumb_status"

    val cat_id = "cat_id"
    val price = "price"
    val item_condition = "item_condition"
    val sold_status = "sold_status"

    val image_1 = "image_1"
    val image_2 = "image_2"
    val image_3 = "image_3"
    val image_4 = "image_4"

    val image_1_thumb = "image_1_thumb"
    val image_2_thumb = "image_2_thumb"
    val image_3_thumb = "image_3_thumb"
    val image_4_thumb = "image_4_thumb"

    val logged_in_User_id = "logged_in_User_id"
    val chat_user = "chat_user"

    val product = "product"
    val product_id = "product_id"
    val seller_id = "seller_id"
    val buyer_id = "buyer_id"
    val record = "record"
    val page_record = "page_record"

    val nextPage = "nextPage"

    val deal = "deal"
    val deal_id = "deal_id"
    val vendor_id = "vendor_id"
    val deal_area = "deal_area"
    val deal_catid = "deal_catid"
    val institute_id = "institute_id"
    val venue = "venue"
    val details = "details"
    val discount = "discount"
    val discount_price = "discount_price"
    val emailid = "emailid"
    val coupon_code = "coupon_code"
    val product_category = "product_category"

    val event_id = "event_id"
    val event_type = "event_type"
    val event_name = "event_name"
    val theme = "theme"
    val gate_fees_type = "gate_fees_type"
    val gate_fees = "gate_fees"
    val event_start_time = "event_start_time"
    val event_end_time = "event_end_time"
    val banner_image_thumb = "banner_image_thumb"
    val logo_image_thumb = "logo_image_thumb"
    val imdb_rating = "imdb_rating"
    val sub_title = "sub_title"

    val meta_tags = "meta_tags"
    val meta_keywords = "meta_keywords"
    val lft = "lft"
    val rght = "rght"
    val parent_id = "parent_id"

    val user = "user"
    val institute = "institute"

    val total_product_views = "total_product_views"
    val total_event_views = "total_event_views"
    val total_event_likes = "total_event_likes"
    val event_like_status = "event_like_status"
    val logged_user_view_status = "logged_user_view_status"


    val old_password = "old_password"
    val new_password = "new_password"

    val HEIGHT = "HEIGHT"

    val rating = "rating"
    val reviews = "reviews"
    val reviewer_id = "reviewer_id"
    val logged_in_user_id = "logged_in_user_id"

    val following_id = "following_id"

    val follow = "follow"
    val follow_status = "follow_status"
    val total_product = "total_product"
    val followers_count = "followers_count"
    val following_count = "following_count"

    val cat_name = "cat_name"
    val deal_category = "deal_category"

    val profile_id = "profile_id"
    val from = "from"

    val task_id = "task_id"
    val url = "url"
    val user_online_time_id = "user_online_time_id"
    val pageStartTime = "pageStartTime"
    val pageEndTime = "pageEndTime"
    val width = "width"
    val height = "height"
    val infScroll = "infScroll"
    val isMobile = "isMobile"
    val snapshot = "snapshot"
    val userAgent = "userAgent"
    val userEvents = "userEvents"
    val events = "events"

    val movies = "movies"
    val movie_id = "movie_id"
    val synopsis = "synopsis"
    val run_time = "run_time"
    val starring = "starring"
    val trailer_link = "trailer_link"
    val genre = "genre"
    val cinema_type_with_time = "cinema_type_with_time"
    val is_view = "is_view"
    val total_movie_views = "total_movie_views"
    val total_deal_views = "total_deal_views"


    val cinema_type = "cinema_type"
    val cinema_time = "cinema_time"

    val eventOffCampus = "eventOffCampus"
    val eventOnCampus = "eventOnCampus"

    val reason_id = "reason_id"
    val reason_desc = "reason_desc"

    val banner_type = "banner_type"

    val item_name = "item_name"
    val item_description = "item_description"
    val campus_name = "campus_name"

    val FOUND = "FOUND"
    val jobs = "jobs"
    val job_type = "job_type"
    val job_timing_type = "job_timing_type"
    val job_timimg_type = "job_timimg_type"

    val company_name = "company_name"
    val company_address = "company_address"
    val industry_type = "industry_type"
    val logo_image = "logo_image"
    val posted_by = "posted_by"
    val designation = "designation"
    val website_url = "website_url"
    val isApplied = "isApplied"

    val LOST_FOUND = "LOST_FOUND"
    val directed_by = "directed_by"
    val ticket_fee = "ticket_fee"

    val product_name = "product_name"
    val campus_id = "campus_id"
    val upload = "upload"
    val refine = "refine"

    val offer_price = "offer_price"
    val range = "range"
    val massage = "massage"

    val count = "count"
    val is_grabbed = "is_grabbed"

    val receiver_id = "receiver_id"
    val sender_id = "sender_id"

    val chat_data = "chat_data"
    val product_data = "product_data"

    val total_product_likes = "total_product_likes"
    val product_like_status = "product_like_status"
    val total_comments = "total_comments"

    val sender_data = "sender_data"

    val item_id = "item_id"
    val followUser = "followUser"
    val Makeoffer = "Makeoffer"
    val makeOffer = "makeOffer"

    val notifyId = "notifyId"

    val LONG_CLICK = "LONG_CLICK"
    val delete = "delete"

    val apply_type = "apply_type"
    val external_link = "external_link"

    val total_notifications = "total_notifications"
    val coupon_id = "coupon_id"
    val PASSWORD = "password"

    /*FirebaseAnalytics Params*/
    val videoUploadingTime = "Video_uploading_time"
    val videoSize = "Video_size"
    val videoDuration = "Video_duration"
    val reTriggeredCount = "Retriggered_count"
    val uploadSpeed = "Internet_uploading_speed"
    val downloadSpeed = "downloadSpeed"
    val Android = "Android"
    val Unable_to_prepare_audio_recorder = "Unable_to_prepare_audio_recorder"
    val Background_count_during_study = "Background_count_during_study"


    /*  PARAMETERS*/

    val API_KEY = "apiKey"
    val API_KEY_VALUE = "1254kloi"
    val first_name = "first_name"
    val last_name = "last_name"
    val email = "email"
    val password = "password"
    val post_code = "post_code"
    val device_type = "device_type"
    val device_id = "device_id"
    val country_id = "country_id"
    val state_id = "state_id"
    val city_id = "city_id"
    val uploadedfile0 = "uploadedfile0"
    val saveForgot = "saveForgot"
    val city = "city"
    val address = "address"
    val about_me = "about_me"
    val notification = "notification"
    val gender = "gender"
    val birthdate = "birthdate"
    val nick_name = "nick_name"
    val category_one = "category_one"
    val category_two = "category_two"
    val category_three = "category_three"
    val comment = "comment"
    val file = "file"
    val coach_id = "coach_id"
    val encodedData = "encodedData"
    val delimiter = ":~"
    val seperator = "|"
    val team_id = "team_id"
    val type = "type"
    val action = "action"
    val accept = 1
    val reject = 2
    val do_not_disturb = 3
    val training_date = "training_date"
    val training_period = "training_period"
    val devicetype = "devicetype"
    val deviceType = "deviceType"
    val login_id = "login_id"
    val follower_id = "follower_id"
    val notify_id = "notify_id"
    val date = "date"
    val dateTime = "dateTime"
    val fitday_id = "fitday_id"
    val user_comments = "user_comments"
    val session_id = "session_id"
    val notification_status = "notification_status"
    val language = "language"
    val time = "time"

    val latitude = "latitude"
    val longitude = "longitude"
    val fb_id = "fb_id"
    val remember = "remember"
    val birthday = "birthday"
    val image = "image"
    val created = "created"
    val title = "title"
    val dataFlow = "dataFlow"
    val user_id = "user_id"
    val id = "id"
    val name = "name"
    val deal_category_id = "deal_category_id"
    val sub_category_id = "sub_category_id"
    val description = "description"
    val value_upto = "value_upto"
    val discount_offer = "discount_offer"
    val starting_date = "starting_date"
    val expiry_date = "expiry_date"
    val trems_and_conditions = "trems_and_conditions"

    val total_deal = "total_deal"
    val thumb = "thumb"


    val herodeals = "herodeals"
    val busines = "busines"

    val sortby = "sortby"
    val lat = "lat"
    val LONG = "long"

    val categories = "categories"
    val deal_type = "deal_type"
    val dealStatus = "dealStatus"
    val postalCode = "postalCode"
    val keyword = "keyword"
    val use_the_offer = "use_the_offer"
    val things_to_remebers = "things_to_remebers"
    val facilities = "facilities"
    val item_detail = "item_detail"
    val volume_of_deal = "volume_of_deal"
    val timing_to = "timing_to"
    val timing_from = "timing_from"
    val valid_on = "valid_on"
    val vendor_delete_deal = "vendor_delete_deal"
    val favourite = "favourite"
    val images = "images"
    val adhocdeal_id = "adhocdeal_id"
    val type_id = "type_id"
    val LIKE_DISLIKE_CLICKED = "LIKE_DISLIKE_CLICKED"

    val category_list = "category_list"
    val business_id = "business_id"
    val about_business = "about_business"
    val contact_name = "contact_name"
    val contact_number = "contact_number"
    val open_hours = "open_hours"
    val address1 = "address1"
    val address2 = "address2"
    val location_address = "location_address"
    val membership_id = "membership_id"
    val amount = "amount"
    val month_of_membership = "month_of_membership"

    val herodeal = "herodeal"
    val adhocdeal = "purchase_adhocdeal"
    val CITY_DATA = "CITY_DATA"
    val current_location = "current_location"
    val other = "other"
    val sta_id = "sta_id"
    val Beer = "Beer"
    val Brewery = "Brewery"
    val beer_type_id = "beer_type_id"
    val brewery_type_id = "brewery_type_id"
    val dealId = "dealId"

    val forLatlng = "forLatlng"
    val total_purchase = "total_purchase"
    val total_redeemed = "total_redeemed"
    val brewery_type = "brewery_type"
    val beer_type = "beer_type"
    val redeem = "redeem"
    val cancel = "cancel"

    val items = "items"
    val actual_cost = "actual_cost"
    val discount_cost = "discount_cost"
    val liked = "liked"
    val realm_Notification = "realm_Notification.realm"
    val business_name = "business_name"
    val deal_title = "deal_title"
    val vendor_name = "vendor_name"
    val thumb_image = "thumb_image"
    val deal_image = "deal_image"
    val vendor_image = "vendor_image"
    val adhoc_deal_id = "adhoc_deal_id"
    val total_price = "total_price"
    val paypal_id = "paypal_id"
    val realm_index_id = "realm_index_id"
    val data = "data"
    val payment_id = "payment_id"
    val total_amount = "total_amount"
    val cart_items = "cart_items"
    val cart_id = "cart_id"
    val no_of_item = "no_of_item"
    val user_range = "user_range"
    val membership_start_date = "membership_start_date"
    val membership_end_date = "membership_end_date"
    val login_from = "login_from"

    val notification_type = "notification_type"
    val purchase_id = "purchase_id"
    val expired = "expired"
    val notification_id = "notification_id"
    val membership_name = "membership_name"
    val membership_amount = "membership_amount"
    val membership_status = "membership_status"
    val membership_discription = "membership_discription"
    val nid = "nid"
    val heard_about_us = "heard_about_us"
    val marker_image = "marker_image"
    val marker_icon = "marker_icon"
    val person = "person"

    val permission = "permission"
    val ADITI = "Aditi"

    val percentage = "percentage"
    val progress = "progress"
    val max = "max"
    val uploadStatus = "uploadStatus"

    val INTENT_MAX = "max"
    val INTENT_PERCENTAGE = "percentage"
    val INTENT_MESSAGE = "message"
    val INTENT_PROGRESS = "progress"
    val INTENT_UPLDCMPLT = "uploadingComlete"
    val INTENT_UPLOADING_STATUS = "uploadingStatus"

    val MSG = "msg"


    val COMPLETE_API_KEY_PARAMS = "COMPLETE_API_KEY_PARAMS"
    val cropped_file = "cropped_file"
    val main_file = "main_file"

    val rectWidth = "rectWidth"
    val rectHeight = "rectHeight"
    val rectTop = "rectTop"
    val rectBottom = "rectBottom"
    val rectLeft = "rectLeft"
    val rectRight = "rectRight"
    val rectCenterX = "rectCenterX"
    val rectCenterY = "rectCenterY"

    val orgImgLink = "orgImgLink"
    val cropImgLink = "cropImgLink"
    val cropImg = "cropImg"
    val orgImg = "orgImg"

    val task = "task"
    val test_details = "test_details"

    val videoUrl = "videoUrl"
    val video_id = "video_id"
    val bucketName = "bucketName"
    val aws_auth = "aws_auth"

    val TRY_CATCH = "try_catch"
}